import { ArrowRight, Signpost } from "lucide-react";
import type { Metadata } from "next";

import { ListToolbar } from "@/components/admin/list-toolbar";
import { PageHeader } from "@/components/admin/page-header";
import { Pagination } from "@/components/admin/pagination";
import { Badge } from "@/components/ui/badge";
import type { Prisma } from "@/generated/prisma/client";
import { db } from "@/lib/db";
import { requirePermission } from "@/lib/session";

export const metadata: Metadata = { title: "Redirects" };

const PAGE_SIZE = 50;

export default async function RedirectsPage({
  searchParams,
}: PageProps<"/admin/redirects">) {
  await requirePermission("settings:view");
  const params = await searchParams;

  const str = (key: string) =>
    typeof params[key] === "string" ? (params[key] as string) : undefined;

  const q = str("q");
  const kind = str("kind");
  const page = Math.max(1, Number.parseInt(str("page") ?? "1", 10) || 1);

  const clauses: Prisma.RedirectWhereInput[] = [];

  if (q?.trim()) {
    const term = q.trim();
    clauses.push({
      OR: [
        { fromPath: { contains: term, mode: "insensitive" } },
        { toPath: { contains: term, mode: "insensitive" } },
      ],
    });
  }

  if (kind === "used") clauses.push({ hitCount: { gt: 0 } });
  if (kind === "unused") clauses.push({ hitCount: 0 });
  if (kind === "services") clauses.push({ toPath: { startsWith: "/services/" } });
  if (kind === "parts") clauses.push({ toPath: { startsWith: "/parts/" } });

  const where: Prisma.RedirectWhereInput = clauses.length ? { AND: clauses } : {};

  const [redirects, total, hitTotals] = await Promise.all([
    db.redirect.findMany({
      where,
      // Most-hit first: the legacy URLs that still matter are the ones people
      // and search engines are actually asking for.
      orderBy: [{ hitCount: "desc" }, { fromPath: "asc" }],
      skip: (page - 1) * PAGE_SIZE,
      take: PAGE_SIZE,
    }),
    db.redirect.count({ where }),
    db.redirect.aggregate({ _sum: { hitCount: true }, _count: true }),
  ]);

  const buildHref = (nextPage: number) => {
    const qs = new URLSearchParams();
    for (const [key, value] of Object.entries(params)) {
      if (typeof value === "string" && value) qs.set(key, value);
    }
    if (nextPage > 1) qs.set("page", String(nextPage));
    else qs.delete("page");
    const s = qs.toString();
    return s ? `/admin/redirects?${s}` : "/admin/redirects";
  };

  return (
    <div>
      <PageHeader
        title="Redirects"
        description={`${hitTotals._count} legacy URLs mapped, ${hitTotals._sum.hitCount ?? 0} hits served`}
      />

      <p className="mb-4 rounded-lg border border-border bg-surface p-3 text-sm text-foreground-muted">
        Generated by the WooCommerce import, one per old product URL. These keep
        search rankings and existing links working after the switchover, so they
        matter most in the weeks right after launch. The hit counter shows which
        old addresses people still use.
      </p>

      <ListToolbar
        searchPlaceholder="Search old or new path…"
        filters={[
          {
            name: "kind",
            label: "Show",
            options: [
              { value: "used", label: "Has been hit" },
              { value: "unused", label: "Never hit" },
              { value: "parts", label: "Points to a part" },
              { value: "services", label: "Points to a service" },
            ],
          },
        ]}
      />

      {redirects.length === 0 ? (
        <div className="rounded-card border border-dashed border-border bg-surface-raised px-6 py-16 text-center">
          <div className="mx-auto mb-4 grid size-12 place-items-center rounded-full bg-surface">
            <Signpost className="size-5 text-foreground-muted" aria-hidden />
          </div>
          <h2 className="font-display font-semibold">No redirects match this view</h2>
        </div>
      ) : (
        <>
          <div className="mb-4 rounded-card border border-border bg-surface-raised">
            <div className="overflow-x-auto">
              <table className="w-full min-w-[40rem] text-sm">
                <thead className="border-b border-border bg-surface text-left">
                  <tr>
                    <th scope="col" className="px-4 py-3 font-medium">
                      Old address
                    </th>
                    <th scope="col" className="px-4 py-3 font-medium">
                      Now goes to
                    </th>
                    <th scope="col" className="px-4 py-3 text-right font-medium">
                      Hits
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {redirects.map((redirect) => (
                    <tr
                      key={redirect.id}
                      className="border-b border-border-subtle last:border-0 hover:bg-surface"
                    >
                      <td className="px-4 py-2.5">
                        <span className="font-mono text-xs break-all">
                          {redirect.fromPath}
                        </span>
                        {!redirect.isActive && (
                          <Badge tone="neutral" className="ml-2">
                            Off
                          </Badge>
                        )}
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="flex items-start gap-1.5">
                          <ArrowRight
                            className="mt-0.5 size-3.5 shrink-0 text-foreground-subtle"
                            aria-hidden
                          />
                          <span className="font-mono text-xs break-all">
                            {redirect.toPath}
                          </span>
                        </span>
                      </td>
                      <td className="px-4 py-2.5 text-right tabular-nums">
                        {redirect.hitCount > 0 ? (
                          <span title={
                            redirect.lastHitAt
                              ? `Last hit ${redirect.lastHitAt.toLocaleString("en-GB")}`
                              : undefined
                          }>
                            {redirect.hitCount}
                          </span>
                        ) : (
                          <span className="text-foreground-subtle">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <Pagination
            page={page}
            pageCount={Math.max(1, Math.ceil(total / PAGE_SIZE))}
            total={total}
            pageSize={PAGE_SIZE}
            buildHref={buildHref}
          />
        </>
      )}
    </div>
  );
}
